name = "friction-ai-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "CHAT_HISTORY"
id = “your-kv-namespace-id”

[vars]
ANTHROPIC_API_KEY = ""
OPENAI_API_KEY = ""
GEMINI_API_KEY = ""
XAI_API_KEY = ""
PERPLEXITY_API_KEY = ""
