name = "friction-ai-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

# KV namespace for analytics and rate limiting
kv_namespaces = [
  { binding = "FRICTION_KV", id = "1d183b6e9b0b4f1fa3725d3ba50a6e9c" }
]

[vars]
ADMIN_EMAIL = "fatboydimsim@gmail.com"
GOOGLE_CLIENT_ID = "37442638167-t8m3fql61v05h01qmvall1bki9k88tim.apps.googleusercontent.com"